apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: master
spec:
  service:
    type: LoadBalancer
    port: 8080
  master:
    basePlugins:
    - name: kubernetes
      version: "1.29.2"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.6.0"
    - name: job-dsl
      version: "1.77"
    - name: kubernetes-credentials-provider
      version: "0.16"
    - name: configuration-as-code
      version: "1.47"
    containers:
    - name: jenkins-master
      #image: jenkins/jenkins:2.235.1-lts
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 60
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
      securityContext:
        runAsUser: 0